# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rails_admin_pdf"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steph Skardal"]
  s.date = "2012-07-13"
  s.email = "steph@endpoint.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "config/locales/pdf.en.yml",
    "lib/rails_admin_pdf.rb",
    "lib/rails_admin_pdf/engine.rb",
    "lib/rails_admin_pdf/version.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "PDF functionality for rails admin"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

